runtime: java11
instance_class: F4

#runtime: java
#env: flex

#handlers:
#  - url: /.*
#    script: this field is required, but ignored

#automatic_scaling:
#  min_num_instances: 1
#  cool_down_period_sec: 180

#readiness_check:
#  check_interval_sec: 40
#  timeout_sec: 30
#  failure_threshold: 2
#  success_threshold: 2
#  app_start_timeout_sec: 180
